"""
Action Models
===============
Pydantic v2 models for action plans, resource allocation,
stakeholder messaging, simulation state, and the full
/analyze response shape.

Used by:
- Agent 4 (ActionPlanner) — output
- Agent 5 (Executor) — input/output
- POST /analyze — response body
"""

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, field_validator

from models.crisis_models import CrisisClassification
from models.signal_models import Signal


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------
class ActionType(str, Enum):
    """
    Types of response actions the system can generate and simulate.
    Maps to real-world crisis response operations.
    """

    TRAFFIC_REROUTE = "TRAFFIC_REROUTE"
    EMERGENCY_DISPATCH = "EMERGENCY_DISPATCH"
    PUBLIC_ALERT = "PUBLIC_ALERT"
    HOSPITAL_PREP = "HOSPITAL_PREP"
    UTILITY_ESCALATION = "UTILITY_ESCALATION"
    MEDIA_UPDATE = "MEDIA_UPDATE"


# ---------------------------------------------------------------------------
# Response Action (Agent 4 Output)
# ---------------------------------------------------------------------------
class ResponseAction(BaseModel):
    """
    A single response action generated by the Action Planner.

    Attributes:
        action_id: Unique identifier (e.g., ACT-001).
        type: Category of response action.
        description: Human-readable description of what to do.
        entity: Responsible entity (e.g., Traffic Police, Rescue 1122).
        priority: Execution priority (1 = highest).
        estimated_impact: Expected outcome description.
        resources_allocated: Dict of resources assigned to this action.
    """

    action_id: str = Field(
        ...,
        description="Unique action identifier (e.g., ACT-001)",
        examples=["ACT-001"],
    )
    type: ActionType = Field(
        ...,
        description="Category of response action",
    )
    description: str = Field(
        ...,
        min_length=1,
        description="Human-readable description of the action",
    )
    entity: str = Field(
        ...,
        min_length=1,
        description="Responsible entity (e.g., Traffic Police, Rescue 1122)",
    )
    priority: int = Field(
        ...,
        ge=1,
        le=10,
        description="Execution priority (1 = highest, 10 = lowest)",
    )
    estimated_impact: str = Field(
        default="",
        description="Expected outcome description",
    )
    resources_allocated: dict = Field(
        default_factory=dict,
        description="Dict of resources assigned (e.g., {'rescue_vehicles': 2})",
    )

    @field_validator("action_id")
    @classmethod
    def validate_action_id(cls, v: str) -> str:
        """Ensure action_id is not blank."""
        stripped = v.strip()
        if not stripped:
            raise ValueError("action_id cannot be empty")
        return stripped


# ---------------------------------------------------------------------------
# Stakeholder Messages (Agent 4 Output)
# ---------------------------------------------------------------------------
class StakeholderMessages(BaseModel):
    """
    Pre-generated notification messages for each stakeholder group.
    Agent 4 creates these based on the crisis type and actions planned.

    Attributes:
        public: Alert message for the general public.
        hospital: Preparation notice for hospitals.
        traffic_police: Instructions for traffic police units.
        utility: Notification for utility companies (CDA, WASA, etc.).
        media: Press statement for media outlets.
    """

    public: str = Field(
        default="",
        description="Alert message for the general public",
    )
    hospital: str = Field(
        default="",
        description="Preparation notice for hospitals",
    )
    traffic_police: str = Field(
        default="",
        description="Instructions for traffic police units",
    )
    utility: str = Field(
        default="",
        description="Notification for utility companies",
    )
    media: str = Field(
        default="",
        description="Press statement for media outlets",
    )


# ---------------------------------------------------------------------------
# Simulation State Models (Agent 5)
# ---------------------------------------------------------------------------
class SimulationBefore(BaseModel):
    """
    System state snapshot BEFORE the crisis response actions are executed.

    Attributes:
        routes: Dict of route names → status (e.g., OPEN, CONGESTED).
        congestion_level: Current traffic congestion (0-10 scale).
        emergency_tickets: List of active emergency ticket IDs.
        active_alerts: List of active alert IDs.
    """

    routes: dict = Field(
        default_factory=dict,
        description="Route names mapped to their status (OPEN, BLOCKED, etc.)",
    )
    congestion_level: int = Field(
        default=0,
        ge=0,
        le=10,
        description="Traffic congestion level (0-10 scale)",
    )
    emergency_tickets: list[str] = Field(
        default_factory=list,
        description="List of active emergency ticket IDs",
    )
    active_alerts: list[str] = Field(
        default_factory=list,
        description="List of active alert IDs",
    )


class SimulationAfter(BaseModel):
    """
    System state snapshot AFTER the crisis response actions are executed.
    Extends the before-state with response time improvement metrics.

    Attributes:
        routes: Dict of route names → updated status.
        congestion_level: Updated congestion level after rerouting.
        emergency_tickets: Updated list of emergency ticket IDs.
        active_alerts: Updated list of active alert IDs.
        response_time_before_min: Original response time (minutes).
        response_time_after_min: Improved response time (minutes).
    """

    routes: dict = Field(
        default_factory=dict,
        description="Route names mapped to updated status",
    )
    congestion_level: int = Field(
        default=0,
        ge=0,
        le=10,
        description="Updated congestion level after response actions",
    )
    emergency_tickets: list[str] = Field(
        default_factory=list,
        description="Updated list of emergency ticket IDs",
    )
    active_alerts: list[str] = Field(
        default_factory=list,
        description="Updated list of active alert IDs",
    )
    response_time_before_min: int = Field(
        default=0,
        ge=0,
        description="Original response time in minutes (before CIRO)",
    )
    response_time_after_min: int = Field(
        default=0,
        ge=0,
        description="Improved response time in minutes (after CIRO)",
    )

    @field_validator("response_time_after_min")
    @classmethod
    def validate_improvement(cls, v: int, info) -> int:
        """Warn if after-time is greater than before-time (should improve)."""
        # Non-blocking: just return the value. Agents may set 0 initially.
        return v


class SimulationResult(BaseModel):
    """
    Complete before/after simulation comparison.
    Saved to Firebase by Agent 5 (Executor).

    Attributes:
        before: System state before response actions.
        after: System state after response actions.
    """

    before: SimulationBefore = Field(
        default_factory=SimulationBefore,
        description="System state before response actions",
    )
    after: SimulationAfter = Field(
        default_factory=SimulationAfter,
        description="System state after response actions",
    )


# ---------------------------------------------------------------------------
# Full Analyze Response (Backend → Flutter)
# ---------------------------------------------------------------------------
class AnalyzeResponse(BaseModel):
    """
    Complete response from the POST /analyze endpoint.
    Contains the full output of all 5 agents in the pipeline.

    This is what the Flutter app receives and renders.

    Attributes:
        incident_id: Unique incident identifier (e.g., INC-2026-001).
        status: Pipeline status ('success', 'partial', 'error').
        processing_time_ms: Total pipeline execution time (milliseconds).
        crisis: Full crisis classification and situation analysis.
        signals_used: List of signals that informed the classification.
        actions: List of response actions generated.
        stakeholder_messages: Pre-generated messages for each stakeholder.
        simulation: Before/after system state comparison.
        agent_trace_id: Reference to the full agent trace log.
    """

    incident_id: str = Field(
        ...,
        description="Unique incident identifier (e.g., INC-2026-001)",
        examples=["INC-2026-001"],
    )
    status: str = Field(
        default="success",
        description="Pipeline status: 'success', 'partial', or 'error'",
    )
    processing_time_ms: int = Field(
        default=0,
        ge=0,
        description="Total pipeline execution time in milliseconds",
    )
    crisis: CrisisClassification = Field(
        ...,
        description="Full crisis classification and situation analysis",
    )
    signals_used: list[Signal] = Field(
        default_factory=list,
        description="List of signals that informed the classification",
    )
    actions: list[ResponseAction] = Field(
        default_factory=list,
        description="List of response actions generated by the planner",
    )
    stakeholder_messages: StakeholderMessages = Field(
        default_factory=StakeholderMessages,
        description="Pre-generated messages for each stakeholder group",
    )
    simulation: SimulationResult = Field(
        default_factory=SimulationResult,
        description="Before/after system state comparison",
    )
    agent_trace_id: str = Field(
        default="",
        description="Reference to the full agent trace log file",
        examples=["TRACE-INC-2026-001"],
    )

    @field_validator("incident_id")
    @classmethod
    def validate_incident_id(cls, v: str) -> str:
        """Ensure incident_id is not blank."""
        stripped = v.strip()
        if not stripped:
            raise ValueError("incident_id cannot be empty")
        return stripped
